### ISSUE TITLE
Plugin adds a permanent TSC status

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-styled-components#1] opened 2019-09-17 02:15 UTC
Plugin adds a permanent TSC to status, even when not editing typescript.

**Comment by fannheyward** [comment] 2019-09-17 02:28
TSC is added by coc-tsserver, looks like tsserver is activated.

**Comment by oblitum** [comment] 2019-09-17 02:30
Yeah but, it's happening now simply by opening nvim, even without any file. Isn't that a bug?

**Comment by fannheyward** [comment] 2019-09-17 02:31
Reproduced it.

**Comment by fannheyward** [comment] 2019-09-17 02:38
Fixed on 0.1.1, thanks for your feedback.

**Closed as completed by fannheyward** 2019-09-17 02:38 UTC
